param(
  [string]$SourceAccount = "deployer",
  [string]$Network = "testnet"
)

$ErrorActionPreference = "Stop"

function Write-Step {
  param([string]$Message)
  Write-Host ""
  Write-Host "=== $Message ==="
}

function Get-FirstMatch {
  param(
    [string]$Text,
    [string]$Pattern
  )

  $Match = [regex]::Match($Text, $Pattern)

  if ($Match.Success) {
    return $Match.Value
  }

  return ""
}

function Run-Cmd {
  param(
    [string]$Command,
    [string]$LogPath
  )

  Write-Host $Command

  cmd.exe /d /s /c "$Command > `"$LogPath`" 2>&1"

  $Output = Get-Content $LogPath -Raw

  Write-Host $Output

  if ($LASTEXITCODE -ne 0) {
    throw "Command failed: $Command"
  }

  return $Output
}

$RepoRoot = Split-Path -Parent $PSScriptRoot
Set-Location $RepoRoot

$WasmPath = Join-Path $RepoRoot "target\wasm32v1-none\release\remittance_contract.wasm"
$DeployLog = Join-Path $RepoRoot "deploy-output.txt"
$TmpLog = Join-Path $RepoRoot "deploy-stdout.tmp"

Write-Step "Check environment"

stellar --version
cargo --version
node -v
npm -v

Write-Step "Use Stellar Testnet"

cmd.exe /d /s /c "stellar network use $Network > `"$TmpLog`" 2>&1"
Get-Content $TmpLog -Raw | Write-Host

Write-Step "Ensure deployer identity exists and is funded"

cmd.exe /d /s /c "stellar keys address $SourceAccount > `"$TmpLog`" 2>&1"

if ($LASTEXITCODE -ne 0) {
  Write-Host "Deployer identity not found. Creating and funding $SourceAccount..."
  cmd.exe /d /s /c "stellar keys generate --fund $SourceAccount --network $Network > `"$TmpLog`" 2>&1"
  Get-Content $TmpLog -Raw | Write-Host
} else {
  Get-Content $TmpLog -Raw | Write-Host
}

cmd.exe /d /s /c "stellar keys fund $SourceAccount --network $Network > `"$TmpLog`" 2>&1"
Get-Content $TmpLog -Raw | Write-Host

cmd.exe /d /s /c "stellar keys address $SourceAccount > `"$TmpLog`" 2>&1"
$AddressOutput = Get-Content $TmpLog -Raw
Write-Host $AddressOutput

$DeployerAddress = Get-FirstMatch $AddressOutput "G[A-Z2-7]{55}"

if (-not $DeployerAddress) {
  cmd.exe /d /s /c "stellar keys public-key $SourceAccount > `"$TmpLog`" 2>&1"
  $AddressOutput = Get-Content $TmpLog -Raw
  Write-Host $AddressOutput
  $DeployerAddress = Get-FirstMatch $AddressOutput "G[A-Z2-7]{55}"
}

if (-not $DeployerAddress) {
  throw "Could not detect deployer public key."
}

Write-Host "Deployer address: $DeployerAddress"

Write-Step "Format, test, and build contract"

cargo fmt --all
cargo test --workspace
cargo build --workspace --target wasm32v1-none --release

if (-not (Test-Path $WasmPath)) {
  throw "WASM file not found at $WasmPath"
}

Write-Step "Deploy contract"

$DeployCommand = "stellar contract deploy --wasm `"$WasmPath`" --source-account $SourceAccount --network $Network --alias remittance_contract"
cmd.exe /d /s /c "$DeployCommand > `"$TmpLog`" 2>&1"
$DeployOutput = Get-Content $TmpLog -Raw
Write-Host $DeployOutput

if ($LASTEXITCODE -ne 0) {
  Write-Host "Direct deploy failed. Trying upload then deploy with wasm hash..."

  $UploadCommand = "stellar contract upload --source-account $SourceAccount --network $Network --wasm `"$WasmPath`""
  cmd.exe /d /s /c "$UploadCommand > `"$TmpLog`" 2>&1"
  $UploadOutput = Get-Content $TmpLog -Raw
  Write-Host $UploadOutput

  if ($LASTEXITCODE -ne 0) {
    throw "WASM upload failed."
  }

  $WasmHash = Get-FirstMatch $UploadOutput "[a-fA-F0-9]{64}"

  if (-not $WasmHash) {
    throw "Could not detect wasm hash after upload."
  }

  $DeployHashCommand = "stellar contract deploy --source-account $SourceAccount --network $Network --wasm-hash $WasmHash --alias remittance_contract"
  cmd.exe /d /s /c "$DeployHashCommand > `"$TmpLog`" 2>&1"
  $DeployOutput = Get-Content $TmpLog -Raw
  Write-Host $DeployOutput

  if ($LASTEXITCODE -ne 0) {
    throw "Contract deploy from wasm hash failed."
  }
}

$ContractId = Get-FirstMatch $DeployOutput "C[A-Z2-7]{55}"

if (-not $ContractId) {
  throw "Could not detect contract ID from deploy output."
}

Write-Host "Contract ID: $ContractId"

Write-Step "Save deployment files"

[System.IO.File]::WriteAllText((Join-Path $RepoRoot "CONTRACT_ID.txt"), $ContractId, [System.Text.UTF8Encoding]::new($false))

$ConfigPath = Join-Path $RepoRoot "frontend\src\contractConfig.ts"
$ConfigContent = Get-Content $ConfigPath -Raw
$ConfigContent = $ConfigContent -replace 'contractId: ".*"', "contractId: `"$ContractId`""
[System.IO.File]::WriteAllText($ConfigPath, $ConfigContent, [System.Text.UTF8Encoding]::new($false))

$DeploymentLines = @(
  "# Deployment Evidence",
  "",
  "Network: Stellar Testnet",
  "",
  "Contract ID: $ContractId",
  "",
  "Deployer address: $DeployerAddress",
  "",
  "Explorer:",
  "https://stellar.expert/explorer/testnet/contract/$ContractId",
  "",
  "Generated by scripts/deploy-and-save.ps1"
)

[System.IO.File]::WriteAllLines((Join-Path $RepoRoot "DEPLOYMENT.md"), $DeploymentLines, [System.Text.UTF8Encoding]::new($false))

Write-Step "Initialize contract"

$InitCommand = "stellar contract invoke --id $ContractId --source-account $SourceAccount --network $Network -- initialize --admin $DeployerAddress"
cmd.exe /d /s /c "$InitCommand > `"$TmpLog`" 2>&1"
$InitOutput = Get-Content $TmpLog -Raw
Write-Host $InitOutput

Write-Step "Create sample transfer interaction"

$CreateCommand = "stellar contract invoke --id $ContractId --source-account $SourceAccount --network $Network -- create_transfer --sender $DeployerAddress --receiver $DeployerAddress --amount 100 --asset_code XLM --memo demo"
cmd.exe /d /s /c "$CreateCommand > `"$TmpLog`" 2>&1"
$CreateOutput = Get-Content $TmpLog -Raw
Write-Host $CreateOutput

$TxHash = Get-FirstMatch $CreateOutput "[a-fA-F0-9]{64}"

if ($TxHash) {
  [System.IO.File]::WriteAllText((Join-Path $RepoRoot "TX_HASH.txt"), $TxHash, [System.Text.UTF8Encoding]::new($false))
}

$FullLog = @(
  "Contract ID: $ContractId",
  "",
  "Deployer address: $DeployerAddress",
  "",
  "Initialize output:",
  $InitOutput,
  "",
  "Create transfer output:",
  $CreateOutput
) -join "`r`n"

[System.IO.File]::WriteAllText($DeployLog, $FullLog, [System.Text.UTF8Encoding]::new($false))

Write-Step "Verify frontend with deployed contract config"

Set-Location (Join-Path $RepoRoot "frontend")
npm install
npm run type-check
npm run build
npm test

Set-Location $RepoRoot

Write-Step "Deployment complete"

Write-Host "Contract ID: $ContractId"

if ($TxHash) {
  Write-Host "Transaction hash: $TxHash"
} else {
  Write-Host "No tx hash detected from CLI output. You can still use deploy-output.txt as interaction evidence."
}

git status